<%@ page contentType="text/html;charset=UTF-8"%>

<%@ page import="java.util.List"%>
<%@ page import="java.util.Map"%>

<%@ page import="com.pratik.pharma.model.Client"%>
<%@ page import="com.pratik.pharma.model.Product"%>
<%@ page import="com.pratik.pharma.model.Scheme"%>

<!DOCTYPE html>

<html lang="en">

<head>

<meta charset="UTF-8">

<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>Create Customer Order</title>


<link
	href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
	rel="stylesheet">


<style>
body {
	background: #f5f7fa;
}

.card {
	border-radius: 10px;
}

.item-row {
	position: relative;
	overflow: visible !important;
	z-index: 1;
}

.item-row:focus-within {
	z-index: 9999;
}

.product-select {
	position: relative;
	z-index: 9999;
}

#itemsContainer {
	overflow: visible !important;
}

.card-body {
	overflow: visible !important;
}

.product-info {
	background: #eef7ff;
	border-radius: 8px;
}

.summary-box {
	min-height: 100px;
}

.summary-value {
	font-size: 22px;
	font-weight: 600;
}
</style>

</head>


<body>


	<div class="container-fluid mt-4 mb-5">


		<!-- =====================================================
         HEADER
         ===================================================== -->

		<div class="d-flex justify-content-between align-items-center mb-4">

			<div>

				<h2>Create Customer Order</h2>

				<p class="text-muted mb-0">Add multiple products to one customer
					order</p>

			</div>


			<a href="<%=request.getContextPath()%>/orders"
				class="btn btn-secondary"> Back to Orders </a>

		</div>


		<!-- =====================================================
         ERROR
         ===================================================== -->

		<%
		String orderError = (String) session.getAttribute("orderError");

		if (orderError != null) {

			session.removeAttribute("orderError");
		%>

		<div class="alert alert-danger">

			<strong>Order Error:</strong>

			<%=orderError%>

		</div>

		<%
		}
		%>


		<!-- =====================================================
         FORM
         ===================================================== -->

		<form id="orderForm" action="<%=request.getContextPath()%>/orders"
			method="post">


			<input type="hidden" name="action" value="create">


			<!-- =================================================
             CUSTOMER
             ================================================= -->

			<div class="card shadow mb-4">


				<div class="card-header bg-primary text-white">

					<h5 class="mb-0">Customer Information</h5>

				</div>


				<div class="card-body">


					<div class="row">


						<div class="col-md-6">


							<label class="form-label"> Customer </label> <select
								name="clientId" id="clientId" class="form-select" required>


								<option value="">-- Select Customer --</option>


								<%
								List<Client> clients = (List<Client>) request.getAttribute("clients");

								if (clients != null) {

									for (Client client : clients) {

										if ("ACTIVE".equalsIgnoreCase(client.getStatus())) {
								%>


								<option value="<%=client.getClientId()%>">

									<%=client.getClientName()%>

								</option>


								<%
								}

								}

								}
								%>


							</select>


						</div>


					</div>


				</div>


			</div>



			<!-- =================================================
             ORDER ITEMS
             ================================================= -->

			<div class="card shadow mb-4">


				<div class="card-header bg-dark text-white">


					<div class="d-flex justify-content-between align-items-center">


						<h5 class="mb-0">Order Items</h5>


						<button type="button" class="btn btn-success btn-sm"
							onclick="addProductRow()">+ Add Product</button>


					</div>


				</div>


				<div class="card-body">


					<div id="itemsContainer">


						<!-- =================================================
                         FIRST ROW
                         THIS IS DIRECTLY GENERATED BY JSP
                         ================================================= -->

						<div class="item-row border rounded p-3 mb-3 bg-light">


							<div class="row g-3 align-items-end">


								<!-- PRODUCT -->

								<div class="col-md-5">


									<label class="form-label"> Product </label> <select
										name="productId" class="form-select product-select" required>


										<option value="">-- Select Product --</option>


										<%
										List<Product> products = (List<Product>) request.getAttribute("products");

										if (products != null) {

											for (Product product : products) {

												if ("ACTIVE".equalsIgnoreCase(product.getStatus())) {
										%>


										<option value="<%=product.getProductId()%>"
											data-name="<%=product.getProductName()%>"
											data-code="<%=product.getProductCode()%>"
											data-price="<%=product.getSellingPrice() == null ? "0" : product.getSellingPrice()%>"
											data-gst="<%=product.getGstRate() == null ? "0" : product.getGstRate()%>"
											data-dosage="<%=product.getDosageForm() == null ? "" : product.getDosageForm()%>"
											data-strength="<%=product.getStrength() == null ? "" : product.getStrength()%>"
											data-unit="<%=product.getUnit() == null ? "" : product.getUnit()%>"
											data-hsn="<%=product.getHsnCode() == null ? "" : product.getHsnCode()%>"
											data-cold="<%=product.isColdChainRequired()%>">


											<%=product.getProductName()%> -

											<%=product.getProductCode()%>


										</option>


										<%
										}

										}

										}
										%>


									</select>


								</div>



								<!-- QUANTITY -->

								<div class="col-md-2">


									<label class="form-label"> Quantity </label> <input
										type="number" name="quantity"
										class="form-control quantity-input" min="1" value="1" required>


								</div>



								<!-- FREE -->

								<div class="col-md-2">


									<label class="form-label"> Free Qty </label> <input type="text"
										class="form-control free-display" value="0" readonly>


								</div>



								<!-- TOTAL -->

								<div class="col-md-2">


									<label class="form-label"> Line Total </label> <input
										type="text" class="form-control line-total-display"
										value="₹0.00" readonly>


								</div>



								<!-- REMOVE -->

								<div class="col-md-1">


									<button type="button" class="btn btn-danger w-100 remove-btn"
										onclick="removeProductRow(this)">X</button>


								</div>


							</div>



							<!-- =================================================
                             PRODUCT INFORMATION
                             ================================================= -->

							<div class="product-info alert alert-info mt-3 mb-0"
								style="display: none;">


								<div class="row g-2">


									<div class="col-md-3">

										<strong> Product: </strong> <span class="info-name"> </span>

									</div>


									<div class="col-md-2">

										<strong> Code: </strong> <span class="info-code"> </span>

									</div>


									<div class="col-md-2">

										<strong> GST: </strong> <span class="info-gst"> </span>%

									</div>


									<div class="col-md-2">

										<strong> HSN: </strong> <span class="info-hsn"> </span>

									</div>


									<div class="col-md-3">

										<strong> Scheme: </strong> <span class="info-scheme">
											No active scheme </span>

									</div>


								</div>


								<div class="row mt-2">


									<div class="col-md-12">

										<strong> Details: </strong> <span class="info-details">
										</span>

									</div>


								</div>


								<div class="cold-chain-warning alert alert-warning mt-2 mb-0"
									style="display: none;">


									<strong> ⚠ Cold Chain Required </strong> <br> This product
									requires temperature-controlled storage and transportation.


								</div>


							</div>


						</div>


					</div>


				</div>


			</div>



			<!-- =================================================
             SUMMARY
             ================================================= -->

			<div class="card shadow mb-4">


				<div class="card-header bg-primary text-white">

					<h5 class="mb-0">Order Summary</h5>

				</div>


				<div class="card-body">


					<div class="row g-3">


						<!-- PRODUCTS -->

						<div class="col-md-3">

							<div class="card bg-light summary-box">

								<div class="card-body">

									<small class="text-muted"> Products </small>


									<div id="summaryProducts" class="summary-value">0</div>

								</div>

							</div>

						</div>


						<!-- SUBTOTAL -->

						<div class="col-md-3">

							<div class="card bg-light summary-box">

								<div class="card-body">

									<small class="text-muted"> Subtotal </small>


									<div class="summary-value">

										₹ <span id="summarySubtotal"> 0.00 </span>

									</div>

								</div>

							</div>

						</div>


						<!-- DISCOUNT -->

						<div class="col-md-3">

							<div class="card bg-light summary-box">

								<div class="card-body">

									<small class="text-muted"> Discount </small>


									<div class="summary-value">

										₹ <span id="summaryDiscount"> 0.00 </span>

									</div>

								</div>

							</div>

						</div>


						<!-- TOTAL -->

						<div class="col-md-3">

							<div class="card bg-light summary-box">

								<div class="card-body">

									<small class="text-muted"> Estimated Total </small>


									<div class="summary-value text-primary">

										₹ <span id="summaryTotal"> 0.00 </span>

									</div>

								</div>

							</div>

						</div>


					</div>


				</div>

			</div>



			<!-- =================================================
             BUTTONS
             ================================================= -->

			<div class="text-end mb-5">


				<a href="<%=request.getContextPath()%>/orders"
					class="btn btn-secondary me-2"> Cancel </a>


				<button type="submit" class="btn btn-primary btn-lg">

					Create Order</button>


			</div>


		</form>


	</div>



	<!-- =========================================================
     JAVASCRIPT
     ========================================================= -->

	<script>


/* =========================================================
   SCHEME DATA
   ========================================================= */

const schemes = {

<%Map<Integer, Scheme> activeSchemes = (Map<Integer, Scheme>) request.getAttribute("activeSchemes");

if (activeSchemes != null) {

	boolean first = true;

	for (Map.Entry<Integer, Scheme> entry : activeSchemes.entrySet()) {

		if (!first) {%>
,
<%}

		first = false;

		Scheme scheme = entry.getValue();%>


    "<%=entry.getKey()%>": {

        name:
            "<%=scheme.getSchemeName()%>",

        type:
            "<%=scheme.getSchemeType()%>",

        minimumQuantity:
            <%=scheme.getMinimumQuantity()%>,

        freeQuantity:
            <%=scheme.getFreeQuantity()%>,

        discountPercentage:
            <%=scheme.getDiscountPercentage() == null ? "0" : scheme.getDiscountPercentage()%>

    }


<%}

}%>

};



/* =========================================================
   INITIALIZE FIRST ROW
   ========================================================= */

document.addEventListener(
    "DOMContentLoaded",
    function() {

        const firstRow =
            document.querySelector(
                ".item-row"
            );


        attachRowEvents(
            firstRow
        );


        updateSummary();

    }
);



/* =========================================================
   ATTACH EVENTS
   ========================================================= */

function attachRowEvents(row) {


    const select =
        row.querySelector(
            ".product-select"
        );


    const quantity =
        row.querySelector(
            ".quantity-input"
        );


    select.addEventListener(
        "change",
        function() {

            calculateRow(row);

        }
    );


    quantity.addEventListener(
        "input",
        function() {

            calculateRow(row);

        }
    );

}



/* =========================================================
   ADD PRODUCT ROW
   ========================================================= */

function addProductRow() {


    const container =
        document.getElementById(
            "itemsContainer"
        );


    const firstRow =
        document.querySelector(
            ".item-row"
        );


    /*
     * Clone the first row.
     *
     * This is the important part.
     * The product options are already present
     * because JSP generated them.
     */

    const newRow =
        firstRow.cloneNode(true);


    /*
     * Reset product
     */

    const select =
        newRow.querySelector(
            ".product-select"
        );


    select.selectedIndex = 0;


    /*
     * Reset quantity
     */

    const quantity =
        newRow.querySelector(
            ".quantity-input"
        );


    quantity.value = 1;


    /*
     * Reset free quantity
     */

    newRow.querySelector(
        ".free-display"
    ).value = 0;


    /*
     * Reset line total
     */

    newRow.querySelector(
        ".line-total-display"
    ).value = "₹0.00";


    /*
     * Hide product info
     */

    newRow.querySelector(
        ".product-info"
    ).style.display =
        "none";


    /*
     * Reset cold chain
     */

    newRow.querySelector(
        ".cold-chain-warning"
    ).style.display =
        "none";


    /*
     * Add row
     */

    container.appendChild(
        newRow
    );


    /*
     * Attach events
     */

    attachRowEvents(
        newRow
    );


    updateRemoveButtons();


    updateSummary();

}



/* =========================================================
   REMOVE PRODUCT ROW
   ========================================================= */

function removeProductRow(button) {


    const rows =
        document.querySelectorAll(
            ".item-row"
        );


    if (rows.length <= 1) {

        alert(
            "At least one product is required."
        );

        return;

    }


    const row =
        button.closest(
            ".item-row"
        );


    row.remove();


    updateRemoveButtons();


    updateSummary();

}



/* =========================================================
   UPDATE REMOVE BUTTONS
   ========================================================= */

function updateRemoveButtons() {


    const rows =
        document.querySelectorAll(
            ".item-row"
        );


    rows.forEach(
        function(row, index) {


            const button =
                row.querySelector(
                    ".remove-btn"
                );


            if (rows.length === 1) {

                button.disabled =
                    true;

            }

            else {

                button.disabled =
                    false;

            }

        }
    );

}



/* =========================================================
   CALCULATE ROW
   ========================================================= */

function calculateRow(row) {


    const select =
        row.querySelector(
            ".product-select"
        );


    const quantityInput =
        row.querySelector(
            ".quantity-input"
        );


    const freeDisplay =
        row.querySelector(
            ".free-display"
        );


    const lineTotal =
        row.querySelector(
            ".line-total-display"
        );


    const productInfo =
        row.querySelector(
            ".product-info"
        );


    const productId =
        select.value;


    /*
     * Nothing selected
     */

    if (!productId) {


        productInfo.style.display =
            "none";


        freeDisplay.value =
            "0";


        lineTotal.value =
            "₹0.00";


        updateSummary();


        return;

    }


    /*
     * Read product directly
     * from the selected option.
     */

    const option =
        select.options[
            select.selectedIndex
        ];


    const productName =
        option.dataset.name || "";


    const productCode =
        option.dataset.code || "";


    const price =
        Number(
            option.dataset.price
        ) || 0;


    const gst =
        Number(
            option.dataset.gst
        ) || 0;


    const dosage =
        option.dataset.dosage || "";


    const strength =
        option.dataset.strength || "";


    const unit =
        option.dataset.unit || "";


    const hsn =
        option.dataset.hsn || "";


    const cold =
        option.dataset.cold === "true";


    const quantity =
        parseInt(
            quantityInput.value
        ) || 0;


    if (quantity <= 0) {

        return;

    }


    /* =====================================================
       SCHEME
       ===================================================== */

    const scheme =
        schemes[
            String(productId)
        ];


    let freeQuantity = 0;

    let discount = 0;


    /*
     * BUY X GET Y FREE
     */

    if (
        scheme
        &&
        scheme.type ===
        "BUY_GET_FREE"
    ) {


        if (
            quantity >=
            scheme.minimumQuantity
        ) {


            freeQuantity =
                Math.floor(
                    quantity /
                    scheme.minimumQuantity
                )
                *
                scheme.freeQuantity;

        }

    }


    /*
     * PERCENTAGE DISCOUNT
     */

    if (
        scheme
        &&
        scheme.type ===
        "PERCENTAGE_DISCOUNT"
    ) {


        if (
            quantity >=
            scheme.minimumQuantity
        ) {


            const gross =
                price *
                quantity;


            discount =
                gross *
                Number(
                    scheme.discountPercentage
                )
                /
                100;

        }

    }


    /* =====================================================
       CALCULATIONS
       ===================================================== */

    const subtotal =
        price *
        quantity;


    const taxable =
        subtotal -
        discount;


    const tax =
        taxable *
        gst /
        100;


    const total =
        taxable +
        tax;


    /* =====================================================
       DISPLAY
       ===================================================== */

    freeDisplay.value =
        freeQuantity;


    lineTotal.value =
        "₹" +
        total.toFixed(2);


    /* =====================================================
       PRODUCT INFO
       ===================================================== */

    productInfo.style.display =
        "block";


    row.querySelector(
        ".info-name"
    ).textContent =
        productName;


    row.querySelector(
        ".info-code"
    ).textContent =
        productCode;


    row.querySelector(
        ".info-gst"
    ).textContent =
        gst.toFixed(2);


    row.querySelector(
        ".info-hsn"
    ).textContent =
        hsn || "-";


    row.querySelector(
        ".info-details"
    ).textContent =
        [
            dosage,
            strength,
            unit
        ]
        .filter(Boolean)
        .join(" | ");


    /* =====================================================
       SCHEME DISPLAY
       ===================================================== */

    const schemeDisplay =
        row.querySelector(
            ".info-scheme"
        );


    if (scheme) {


        if (
            scheme.type ===
            "BUY_GET_FREE"
        ) {


            schemeDisplay.textContent =
                scheme.name
                +
                " | Free: "
                +
                freeQuantity;

        }

        else {


            schemeDisplay.textContent =
                scheme.name
                +
                " | Discount: "
                +
                Number(
                    scheme.discountPercentage
                ).toFixed(2)
                +
                "%";

        }

    }

    else {


        schemeDisplay.textContent =
            "No active scheme";

    }


    /* =====================================================
       COLD CHAIN
       ===================================================== */

    const coldWarning =
        row.querySelector(
            ".cold-chain-warning"
        );


    if (cold) {

        coldWarning.style.display =
            "block";

    }

    else {

        coldWarning.style.display =
            "none";

    }


    updateSummary();

}



/* =========================================================
   UPDATE SUMMARY
   ========================================================= */

function updateSummary() {


    const rows =
        document.querySelectorAll(
            ".item-row"
        );


    let productCount = 0;

    let subtotal = 0;

    let discount = 0;

    let total = 0;


    rows.forEach(
        function(row) {


            const select =
                row.querySelector(
                    ".product-select"
                );


            const quantityInput =
                row.querySelector(
                    ".quantity-input"
                );


            if (!select.value) {

                return;

            }


            const option =
                select.options[
                    select.selectedIndex
                ];


            const price =
                Number(
                    option.dataset.price
                ) || 0;


            const gst =
                Number(
                    option.dataset.gst
                ) || 0;


            const quantity =
                parseInt(
                    quantityInput.value
                ) || 0;


            if (quantity <= 0) {

                return;

            }


            const rowSubtotal =
                price *
                quantity;


            let rowDiscount = 0;


            const scheme =
                schemes[
                    String(
                        select.value
                    )
                ];


            if (
                scheme
                &&
                scheme.type ===
                "PERCENTAGE_DISCOUNT"
                &&
                quantity >=
                scheme.minimumQuantity
            ) {


                rowDiscount =
                    rowSubtotal
                    *
                    Number(
                        scheme.discountPercentage
                    )
                    /
                    100;

            }


            const taxable =
                rowSubtotal -
                rowDiscount;


            const tax =
                taxable *
                gst /
                100;


            const rowTotal =
                taxable +
                tax;


            productCount++;


            subtotal +=
                rowSubtotal;


            discount +=
                rowDiscount;


            total +=
                rowTotal;

        }
    );


    document.getElementById(
        "summaryProducts"
    ).textContent =
        productCount;


    document.getElementById(
        "summarySubtotal"
    ).textContent =
        subtotal.toFixed(2);


    document.getElementById(
        "summaryDiscount"
    ).textContent =
        discount.toFixed(2);


    document.getElementById(
        "summaryTotal"
    ).textContent =
        total.toFixed(2);

}



/* =========================================================
   FORM VALIDATION
   ========================================================= */

document.getElementById(
    "orderForm"
).addEventListener(
    "submit",
    function(event) {


        /*
         * Customer
         */

        const client =
            document.getElementById(
                "clientId"
            );


        if (!client.value) {

            event.preventDefault();

            alert(
                "Please select a customer."
            );

            client.focus();

            return;

        }


        /*
         * Rows
         */

        const rows =
            document.querySelectorAll(
                ".item-row"
            );


        const selectedProducts =
            new Set();


        let valid =
            true;


        rows.forEach(
            function(row) {


                const select =
                    row.querySelector(
                        ".product-select"
                    );


                const quantity =
                    row.querySelector(
                        ".quantity-input"
                    );


                /*
                 * Product required
                 */

                if (!select.value) {

                    valid = false;

                    return;

                }


                /*
                 * Quantity required
                 */

                if (
                    !quantity.value
                    ||
                    parseInt(
                        quantity.value
                    ) <= 0
                ) {

                    valid = false;

                    return;

                }


                /*
                 * Duplicate product
                 */

                if (
                    selectedProducts.has(
                        select.value
                    )
                ) {

                    valid = false;

                    return;

                }


                selectedProducts.add(
                    select.value
                );

            }
        );


        if (!valid) {

            event.preventDefault();


            alert(
                "Please select valid products and quantities. Do not add the same product twice."
            );


            return;

        }

    }
);


/* =========================================================
   INITIAL BUTTON STATE
   ========================================================= */

updateRemoveButtons();


</script>


</body>

</html>